[config]
# Folder where the generated results, e.g. *.html and *.png, will be stored. It will be created if it doesn't exist.
resultsDir = results
# Whether to generate HTML files for the test cases. If False, only images will be generated.
genHTML = True
# Whether to generate images for the test cases. If False, only HTML files will be generated.
genImage = True
# Whether to generate a guide curves for the test cases. If False, the guide curves will not be generated.
genGuide = False
# Whether to generate include cursor data in the HTML output. If False, the cursor data will not be included in the HTML output.
genCursorHTML = True
# Whether to generate a seperate PDF file containing all the cursor data. If False, the cursor data will not be included in a seperate PDF file.
genCursorPDF = False
# The image format for the generated images. Supported formats include png, jpg, svg, etc.
imageFormat = png
# The number of columns to use when displaying the test cases in the generated HTML files. This setting is only applicable if genHTML is True.
htmlColumns = 2
# The number of columns to use when displaying the images in the generated HTML files. This setting is only applicable if genHTML is True and genImage is True.
imageColumns = 3
# The number of columns to use when displaying the cursor data in the generated HTML files. This setting is only applicable if genHTML is True and genCursorHTML is True.
htmlCursorColumns = 2
# The number of processes to use for parallel processing when generating the results. This setting can help speed up the generation process by utilizing multiple CPU cores. 
# Set this to 1 to disable parallel processing - useful for debugging or if you have limited resources. 
# Set this to a higher number to speed up the generation process, but be mindful of your system's capabilities and the workload. If set to 0, it will use all available CPU cores. 
processes = 8
# The path to the Excel file containing the test cases that was used to generate the PSCAD and PowerFactory simulation data.
# This file is used to extract the test case information and used in generating the guide curves in the HTML output.
testcaseSheet = ..\testcases.xlsx

[Simulation data paths]
# The paths to the folders containing the simulation data for the EMT and RMS test cases. These paths are used to locate the simulation data files that will be processed to generate the results.
# Make sure to update these paths to point to the correct locations of your simulation data.
EMT = ..\export\MTB_10122025135456
RMS = ..\export\MTB_23122025140547
