[General]
# Test case sheet path
Casesheet path = .\testcases.xlsx
#Path to export result files (relative to execute.py)
Export folder = export

[Python]
# Optional path to append to the python path
Python path = 

[PSCAD]
#Volley size. This should always be at least 1 less than the number of processors available.
Volley = 8
# "Tracing = False", corrisponds to "Affinity Type" 0, which means that none of the parallel simulation instance will send simulation data back to display in graphs during the simulation run.
# This can improve performance, but you won't be able to see the live state of the simulation in the GUI until it finishes.
# "Tracing = True", corrisponds to "Affinity Type" 2 ('ALL'), which means that all the parallel simulation instance will send simulation data back to display in graphs during the simulation run.
# This can significantly increase overhead and reduce performance, especially for large simulations, but it allows you to see the current state of the simulation in real time.
# This can be useful for monitoring and debugging, but may also increase overhead and reduce performance. 
Tracing = False
# With "State animation" False, the schematic remains static.
# With "State animation" True, as the simulation runs, the PSCAD GUI constantly updates the schematic to show the current state of the power system.
State animation = False
# With "Only in use channels" False, the simulation engine calculates and prepares every single signal and component state in the entire project.
# With "Only in use channels" True, the engine only processes and buffers data for signals that are explicitly connected to an Output Channel or a Plot.
Only in use channels = True
# Fortran version when running "execute_pscad.py" from the command line
Fortran version = Intel 19.2.49496 (64-bit)
# Workspace path when running "execute_pscad.py" from the command line
Workspace = ..\Solbakke.pswx

[PowerFactory]
# PowerFactory parallel task automation. 
Parallel = True
# As per 2023 SP5 there is a bug in PF that causes QDSL blocks to be ignored in parallel simulations.
# PowerFactory temporary workaround: QDSL controller sometimes fails when not in same grid as calc. relevant statgens.
# The QDSL controller will be copied to the following grid. Disable by setting to empty string:
QDSL copy grid =
